
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.demo;

import luban.*;
import com.google.gson.JsonElement;


public final class TbRewardsss {
    private final java.util.HashMap<Integer, cfg.demo.my123> _dataMap;
    private final java.util.ArrayList<cfg.demo.my123> _dataList;
    
    public TbRewardsss(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, cfg.demo.my123>();
        _dataList = new java.util.ArrayList<cfg.demo.my123>();
        
        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            cfg.demo.my123 _v;
            _v = cfg.demo.my123.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, cfg.demo.my123> getDataMap() { return _dataMap; }
    public java.util.ArrayList<cfg.demo.my123> getDataList() { return _dataList; }

    public cfg.demo.my123 get(int key) { return _dataMap.get(key); }

}
