
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

import luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class ItemExchange extends AbstractBean {
    public ItemExchange(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        num = _buf.get("num").getAsInt();
    }

    public static ItemExchange deserialize(JsonObject _buf) {
            return new cfg.item.ItemExchange(_buf);
    }

    /**
     * 道具id
     */
    public final int id;
    /**
     * 道具数量
     */
    public final int num;

    public static final int __ID__ = 1814660465;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "(format_field_name __code_style field.name):" + id + ","
        + "(format_field_name __code_style field.name):" + num + ","
        + "}";
    }
}

