#server:
#  port: 8090


#dubbo:
#  application:
#    name: consumer-service
#    qos-port: 23333
#  registry:
#    address: nacos://127.0.0.1:8848
    #use-as-config-center: false
    #use-as-metadata-center: false

#spring:
#  application:
#    name: HttpServer
