
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import luban.*;
import com.google.gson.JsonElement;

public final class Tables
{

    public  interface  IJsonLoader {
        JsonElement load(String file) throws java.io.IOException;
    }

    private final cfg.item.TbItem _tbitem;
    public cfg.item.TbItem getTbItem() { return _tbitem; }
    private final cfg.demo.TbRewardsss _tbrewardsss;
    public cfg.demo.TbRewardsss getTbRewardsss() { return _tbrewardsss; }

    public Tables(IJsonLoader loader) throws java.io.IOException {
        _tbitem = new cfg.item.TbItem(loader.load("item_tbitem")); 
        _tbrewardsss = new cfg.demo.TbRewardsss(loader.load("demo_tbrewardsss")); 
    }
}

