
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class Item extends AbstractBean {
    public Item(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        desc = _buf.get("desc").getAsString();
        price = _buf.get("price").getAsInt();
        upgradeToItemId = _buf.get("upgrade_to_item_id").getAsInt();
        { if (_buf.has("expire_time") && !_buf.get("expire_time").isJsonNull()) { expireTime = _buf.get("expire_time").getAsLong(); } else { expireTime = null; } }
        batchUseable = _buf.get("batch_useable").getAsBoolean();
        quality = _buf.get("quality").getAsInt();
        exchangeStream = cfg.item.ItemExchange.deserialize(_buf.get("exchange_stream").getAsJsonObject());
        { com.google.gson.JsonArray _json0_ = _buf.get("exchange_list").getAsJsonArray(); exchangeList = new java.util.ArrayList<cfg.item.ItemExchange>(_json0_.size()); for(JsonElement _e0 : _json0_) { cfg.item.ItemExchange _v0;  _v0 = cfg.item.ItemExchange.deserialize(_e0.getAsJsonObject());  exchangeList.add(_v0); }   }
        exchangeColumn = cfg.item.ItemExchange.deserialize(_buf.get("exchange_column").getAsJsonObject());
    }

    public static Item deserialize(JsonObject _buf) {
            return new cfg.Item(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 名字
     */
    public final String name;
    /**
     * 描述
     */
    public final String desc;
    /**
     * 价格
     */
    public final int price;
    /**
     * 引用当前表
     */
    public final int upgradeToItemId;
    /**
     * 过期时间
     */
    public final Long expireTime;
    /**
     * 能否批量使用
     */
    public final boolean batchUseable;
    /**
     * 品质
     */
    public final int quality;
    /**
     * 道具兑换配置
     */
    public final cfg.item.ItemExchange exchangeStream;
    public final java.util.ArrayList<cfg.item.ItemExchange> exchangeList;
    /**
     * 道具兑换配置
     */
    public final cfg.item.ItemExchange exchangeColumn;

    public static final int __ID__ = 2289459;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "(format_field_name __code_style field.name):" + id + ","
        + "(format_field_name __code_style field.name):" + name + ","
        + "(format_field_name __code_style field.name):" + desc + ","
        + "(format_field_name __code_style field.name):" + price + ","
        + "(format_field_name __code_style field.name):" + upgradeToItemId + ","
        + "(format_field_name __code_style field.name):" + expireTime + ","
        + "(format_field_name __code_style field.name):" + batchUseable + ","
        + "(format_field_name __code_style field.name):" + quality + ","
        + "(format_field_name __code_style field.name):" + exchangeStream + ","
        + "(format_field_name __code_style field.name):" + exchangeList + ","
        + "(format_field_name __code_style field.name):" + exchangeColumn + ","
        + "}";
    }
}

