// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbHelloRpc.proto

package grpc.demo.proto;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgresp = 1;</code>
   */
  java.lang.String getMsgresp();
  /**
   * <code>string msgresp = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgrespBytes();
}
